### PR TITLE
fix: downstream builds are now using 'jx step create pr'

### LINKED ISSUE #5396: jenkins-x-builder-base update PR doesn't update Dockerfile.gobase or Dockerfile.mavenbase
It only updates the actual `Dockerfile`s in subdirectories, not the `Dockerfile.*base`s that are used in a number of the `Dockerfile`s, so their base image never changes.

### PR DESCRIPTION
**Pull request by garethjevans**
fixes https://github.com/jenkins-x/jx/issues/5396

### CODE REVIEW

**Comment by abayer** [comment]
Can we minimize the calls? I know we’re stuck with two calls (Docker and regex), but that would still be better than five. =) Each create pr call after the first results in the downstream PR getting kicked twice more, so things get ugly very quickly.

**Comment by garethjevans** [comment]
@abayer we would need to enhance `jx step create pr regexp` & `jx step create pr docker` to reduce the calls.  It currently only supports a single arg

**Comment by abayer** [comment]
Ugh, I got confused with `chart`. Welp, guess I know what I’m doing today. =)

**Comment by abayer** [comment]
Well, either that or I finally code up a way to batch up all the `create pr` calls to not actually push until they’re all done.

**Comment by abayer** [comment]
@garethjevans fyi - https://github.com/jenkins-x/jx/pull/5390

**Comment by abayer** [comment]
@garethjevans fyi - https://github.com/jenkins-x/jx/issues/5396 - I'm gonna figure this one out today.

**Comment by abayer** [comment]
oh, wait, that'll get fixed by moving to `jx step create pr docker` in the first place! ha!

**Pull request merged**
